### PR TITLE
Test updates

### PR DESCRIPTION
**Pull request by josibake**
Adds three new test cases:

* test lexicographic sort with outputs
* test empty inputs
* test no relevant outputs

Also does some cleanup by removing amount from the test and making the tests no longer rely on a specific ordering of recipients.

### CODE REVIEW

**Comment by cygnet3** [comment]
This post is about the test vectors, so may be more fitting on the BIP352 thread.

Regarding loosening the constraint with the order of recipients:

> the tests now check that the generated / found outputs match the expected.n_outputs field and then proceed to check that each one of their generated / found outputs exist in expected.outputs

I think this does not check for one specific kind of bug: where `n` does not increment correctly when paying multiple labels multiple times.

In other words, this is allowed:

```
output_label_A_n_0
output_label_B_n_1
```
and this is also allowed:

```
output_label_B_n_0
output_label_A_n_1
```

but this is NOT allowed:
```
output_label_A_n_0
output_label_B_n_0
```

However, since both addresses are present in the `expected.outputs`, it will not fail the assertion.

I think one way to fix this if to change the test vector format slightly, to group the outputs by their valid alternatives, like so:

```json
"expected": {
    "outputs": [
        [
        "output_label_A_n_0",
        "output_label_B_n_0"
        ],
        [
            "output_label_A_n_1",
            "output_label_B_n_1",
        ]
    ]
}
```

then in rust, we can do this:

```rust
    // could add a `n_outputs`, or check the length of the outer array
    assert!(expected.outputs.len() == sending_outputs.len())

    // we loop over the expected outputs instead of sending outputs
    for output_array in &expected.outputs {
        // we check if 1 out these outputs is present in our sending_outputs
        output_array.iter().any(|o| sending_outputs.contains(&o)
    }
```

**Comment by josibake** [comment]
> I think this does not check for one specific kind of bug: where `n` does not increment correctly when paying multiple labels multiple times.

Great catch! From a test structure standpoint, I think it might be easier to just include a list with all possible permutations, like so:

```
"expected": {
    outputs: [
        [
            output1, output2, output3
        ],
        [
            output1', output2', output3'
        ],
        ...
    ]
}
```

.. where each sub list is a valid output set. This keeps the tests simple for the cases where this doesn't matter (the majority of the test cases), and then for the test cases where multiple valid output sets are possible, you just iterate through each possible output set until you match one. Can also get rid of the `n_outputs` field this way, since each valid output set is exactly the same size.

**Comment by josibake** [comment]
Update based on your feedback @cygnet3, thanks for the review!

**Comment by cygnet3** [comment]
nice, looks good

**Pull request merged**
